# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kabkOfzWqnbxq2fjxxZkGclNZGuGo8DF

**First , i wanted to see how many columns and lines do i have so i can create a column guide on what each column stands for**
"""

import pandas as pd
df=pd.read_csv('sample_data/dataset.csv' , on_bad_lines='skip')
print(f'shape:{df.shape}')
print(f'columns:{ len(df.columns)}')
print("/nFirst 3 rows :")
print(df.head(3))

"""**i m gonna start analyzing the dataset , debuting the essay with a brief answer on what is the dataset ?**"""

print ("="*25)
print ("Dataset Overview")
print("="*25)
print(f"Total Tracklist : {len(df):,}")
print(f"Columns : {len(df.columns)}")
print(f"Unique Tracks : {df['track_name'].nunique()}")
print('\n'+'='*25)
print("Genres")
print('='*25)
print(df['track_genre'].value_counts().head(10))
print('\n'+'='*25)
print("Artists")
print('='*25)
print(df['artists'].value_counts().head(10))
print('\n'+'='*25)
print("Popularity stas")
print('='*25)
print(df['popularity'].describe())
print('\n'+'='*25)
print("Missing values")
print ("="*25)
print(df.isnull().sum()[df.isnull().sum()>0])
print('\n'+'='*25)
print("Duplicate values")
print ("="*25)
print(f"Duplicates rows :{df.duplicated().sum()}")

"""**I found 114000 tracks with 73638 unique ones , this means the same tracks appears with diffrent genres  ?**"""

print ("Top Tracks by frequency:")
print(df['track_name'].value_counts().head(10))
print(df[df['track_name'] == 'To Begin Again'][['track_name','artists','track_genre', 'popularity']])

"""**On Popularity Distribution**"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,5))
sns.histplot(df['popularity'], bins=50,kde=True ,color='hotpink')
plt.title('Popularity Distribution')
plt.xlabel('Popularity score 0-100')
plt.ylabel('Number of tracks')
plt.axvline(df['popularity'].mean(), color='red', linestyle='--', linewidth=2,label=f'Mean :{df['popularity'].mean():.1f}')
plt.legend()
plt.show()
plt.savefig('Popularity Distribution')



"""Popularity can be a bias when it comes to detecting a hit song or not , So i deciced to inspect the tracks by the "explicity " , Let's see : Do explicit songs score higher or lower ?"""

print ("="*25)
print ( "Explicit VS Clean")
print ("="*25)
exp_stats=df.groupby("explicit")['popularity'].agg(['mean','count','std'])
print(exp_stats)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))
plt.title('Popularity Distribution by Explicit')
plt.ylabel('Popularity score 0-100')
plt.xlabel('Track selection')
sns.boxplot(x='explicit', y='popularity', data=df ,palette=['lightblue', 'purple'])
plt.savefig('explicit _vs_clean.png',dpi=150, bbox_inches='tight')
plt.show()

"""Explicit songs average 3.5 points higher in popularity , but with only 9,747 tracks vs 104,253 clean tracks , this difference may reflect genre bias or release strategy rather than content alone . so the only question to answer here is , Why explicit songs are more popular ?

Testing on 2 Hypthesis:
1-Explicit songs are mostly hip-hop/Rap
2-Have more energy (Danceability)?
"""

print("="*50)
print("Genres of explicit songs")
print("="*50)
print(df[df['explicit']==1]['track_genre'].value_counts().head(10))
print("\n"+"="*50)
print("Genres of clean songs")
print("="*50)
print(df[df['explicit']==0]['track_genre'].value_counts().head(10))

print("="*50)
print("Energy and Danceability")
print("="*50)
print(df.groupby('explicit')[['danceability','valence', 'tempo']].mean())

"""Explicit songs score 3.5 points higher in popularity because they cluster in high-engagement genres (hip-hop, comedy , metal , emo ) and are more dancebale (0.64 vs 0.56). Meanwhile , clean songs tend be "Boring" :/ and are dominated by background muisc (ASMR for study , sleep , relax ..) that people rarely rate or share on media . Another question now , does Danceability correlate with popularity ?"""

import pandas as pd
df=pd.read_csv('sample_data/dataset.csv' , on_bad_lines='skip')
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,6))
sns.scatterplot( x='danceability', y='popularity',data=df , alpha=0.3, color='purple')
plt.title('danceability vs popularity', fontsize=14 , fontweight='bold')
plt.xlabel('Danceability (0=not danceable , 1=very danceable)')
plt.ylabel('Popularity (0-100)')
sns.regplot(x='danceability', y='popularity', data=df , scatter=False , color='red', line_kws={'linewidth':2})

plt.savefig('danceability_vs_popularity.png',dpi=150, bbox_inches='tight')

"""The scatter plot looks like a giant purple cloud with no clear trend . The red line is almost flat .
--> Danceability tells you almost  nothing about popularity.
"""

correlation=df['danceability'].corr(df['popularity'])
print(f"Correlation between Danceability and Popularity : {correlation:.3f}")

"""Despite explicit songs being more danceable and more popular , danceability alone has almost no correlation with popularity (r=0.013)--meaning other factors drive what makes a song hit .

So can we predict POPULARITY ? and what exact features matter the most ?
"""

features=['danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo']
print("="*50)
print("Feature Correlations with popularity")
print("="*50)
correlations=[]
for feature in features :
  corr=df[feature].corr(df['popularity'])
  correlations.append((feature,corr))
  print(f"{feature:20s} : {corr:.4f}")
correlations.sort(key=lambda x:abs(x[1]), reverse=True)
print("\n"+"="*50)
print("Ranked By Strength(absolute value)")
print("="*50)
for i , (feature , corr) in enumerate ( correlations,1):
  direction="UP" if corr > 0 else "DOWN"
  print(f"{i}. {feature:20s} : {corr:.4f} ({direction})")

"""Valence is NEGATIVE --> Sad songs are slightly more popular ! Breakup anthem , emo , Late night vibes ..
Energy is Negative --> Chill beates over Bnagers ( classical over Afro is Crazyyyy)
All correlations are tiny --> Audio features alone CANNOT predict hits .
What makes a song popular is not how it sounds , it's who made it , when it dropped , how it was marketed , TikTok Trends , playlist placement and pure luck . Audio features are almost irrelevant.

Predict Popularity from Audio Features:
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

features=["danceability","energy", "loudness", "speechiness", "acousticness", "instrumentalness", "liveness", "valence","tempo"]

# Drop rows with NaN values in the features or 'popularity' column
df_cleaned = df.dropna(subset=features + ['popularity'])

x = df_cleaned[features]
y = df_cleaned['popularity']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("="*50)
print("Model Results")
print("="*50)
print(f'Mean Squared Error : {mse:.2f}')
print(f'R-squared : {r2:.4f}')
print(f"\nR-squared :{r2*100:.1f}% of popularity variance is explained by these features")
print("="*50)
for feature , coef in zip(features,model.coef_):
  direction="UP" if coef >0 else "DOWN"
  print(f"{feature:20s} : {coef:.4f} {direction}")

"""**I trained a Linear Regression Model on 114,00 Spotify Tracks using 9 audio features . It explained only 4.7% of Popularity variance .**
Proving that what a song sounds like has almost no bearing on wether it becomes a hit or not .Success is driven by Artist fame , marketing , timing , cultural moments that audio data cannot capture and so we conclude the absence of a pattern that tracks a critirea of the song.
"""